language: node_js
node_js:
  - node
script:
  - docker build -t kastnerorz/shu-online-judge-fe:latest .
deploy:
  - true:
      all_branches: true
      tags: true
    provider: script
    script: bash docker_push
env:
  global:
    - secure: eF4FYchZJFP9fIGf0EoiOAjRXyAPCztqJFV1DnXxq+qZDdNl5PSgDtuzBOgvNUpu0mXJSFAIqaZHpZe3DNslYFrgaoYyYevl9cooZQyDGszOZtOdRxkqhsg7Cv1aLL4Wnsk06MYnxJwactntkFNECwtNc4yczSkdDw72mE++eYBSvzyw15RPlqc4RD4zQs+TFz60mDkKIwqGFjM5Q42GuE6OSZtaJRgt1bt0cDnjSJOGNTMTcoxcT1tY6QXTT/a6jFKGL954fEwCFjD0nF5yMARYU3r/cPyMXKDsHOHNvtCI75WRiV0XF8uaMQGmPMkBAM2EKtgEESnjG3mwNu8av3IrFTgcy+xPFPMjhSVTwgF/1ymdubI5HWT71QpEqKcBSPdqSEyPuAqDAb0jETeP01hd2yhq6SO9H5dITc8maONvjp0g9j77F4j975cP9c3YUTEfm6DqzFflrx+VBcIu/lBaP22pCNSG9m0NfNlUR3iQ7EhTMdmqM38Vr7vor2Di7cbUO5z64OijqjWTo0qCVUHizP2uh0aN5RJODPMHCx+l7CpFMDJ7orhsX0FyE6Gk7aFSG/NW2dEOh8sqyZCBKGZCKtJ3cZqVlumevbftv9NDmdSCvpTdd5ej74AmAjIJ5NqxHhHJr03HB71QwLY0Jg20hStUsaYJGc748CLl8gA=
    - secure: LlRYMig2jciMOn+fLxQmY1p7nvvJqqJOB3nEwaQkWxX3g7F//0Ngtw0uh0hNhWB6dAvHbDlj7rLlojbQZBwoWUAzjhxbZFpu4h/GJZSa3l9KSSD90pG5Xgj+9z6SjFpXQkVTpnd3CWIRE5ZXK85PefBiL9ss6ERySaW96dgI1aJjf2dw5MdULqCLwQaOGWz6UFLpyauLhAVvPL/UMHFN909r06WqmiBnn1KGmBrNvomKLg6ujf0ryXzZHoxW9bCffODPOdBjsQDirj2uKcm96GZ28ogwKJP8JMA7wo+l9asQCx2WrvqxJiR/VHnsH3W2PV8nxxe8NkNGbTxpYAGow7YgKiTAZFT8MNuG8Ra6eMCH9tr4rOBoYo0L/YH8LyvUmALcq/X1M7ze23+Z1sHAm7IMs/rcINOUC4+wpmEuVNFGxvCipBy5nCiewvJyq3VuGXtH6TW1xWYYxCpdNbAAwN2TdtaciJ7hz+r3hFd2twvkgma1PaBCfxzwhOrni2U4MenIaEqszX+HwU/p5CLKOYifJkGEegA1gutSwRkye/a7mTkWiyG8k1hcr22wwOtXA1ODnx8eRK75aEiKlQbpbBtcoiobf/EJGGImn9S+1mZU9bLEviPZKzGoJyV3rs8w9koSLw95ZTzjqO6GGQho19rvIVxGMi2BZluE7hCWRE0=
